# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - ps: (new-object net.webclient).DownloadFile('https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.0.exe', 'C:\projects\JAGS-4.3.0.exe')
  - cmd: C:\projects\JAGS-4.3.0.exe /S
cache:
  - C:\RLibrary

environment:
  # NOT_CRAN: true
  # env vars that may need to be set, at least temporarily, from time to time
  # see https://github.com/krlmlr/r-appveyor#readme for details
  # USE_RTOOLS: true
  # R_REMOTES_STANDALONE: true

# Adapt as necessary starting from here

  matrix:
  # - R_VERSION: devel
  #   NOT_CRAN: true
  #   R_CHECK_ARGS: "--no-manual"
  #   USE_RTOOLS: true
  #   WARNINGS_AS_ERRORS: OFF
    
  # - R_VERSION: devel
  #   NOT_CRAN: true
  #   R_CHECK_ARGS: "--no-manual"
  #   USE_RTOOLS: true
  #   WARNINGS_AS_ERRORS: OFF
    
  - R_VERSION: stable
    NOT_CRAN: false
    USE_RTOOLS: true
    WARNINGS_AS_ERRORS: OFF
    
  - R_VERSION: stable
    NOT_CRAN: false
    USE_RTOOLS: true
    WARNINGS_AS_ERRORS: OFF
    
build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

notifications:
 - provider: Email
   to:
     - tomaug@ceh.ac.uk
   subject: 'r-appveyor build {{status}}'                  # optional
   message: "https://ci.appveyor.com/project/krlmlr/r-appveyor"    # optional
   on_build_success: false
   on_build_failure: true
   on_build_status_changed: true
